name: Android CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout codes
      - name: Checkout code
        uses: actions/checkout@v4

      # Prepare local properties
      - name: Prepare local properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      # Specify changes
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            android:
              - 'app/src/**'
              - 'build.gradle.kts'
              - 'app/build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle.properties'
              - 'gradle/**'

      # Prepare Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # Setup gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Cache NDK
      - name: Cache NDK
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/ndk
            ~/.android/build-cache
          key: ndk-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts', '**/local.properties') }}
          restore-keys: |
            ndk-${{ runner.os }}-

      # Grant permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ### From here conditional steps ###
      # Enable KVM for more faster instrumented test
      - name: Enable KVM
        if: steps.changes.outputs.android == 'true'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger

      # Find cache and if it exists get it
      - name: AVD cache
        if: steps.changes.outputs.android == 'true'
        uses: actions/cache@v4
        id: avd-cache # Specify a unique GitHub Actions ID for the cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33

      # Create AVD...
      # (If cache was hit, skip this step and use AVD from cache)
      - name: Create AVD and generate snapshot for caching
        if: steps.changes.outputs.android == 'true' && steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # ...and run instrumented tests with AVD
      - name: Run instrumented tests from snapshot
        if: steps.changes.outputs.android == 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./gradlew --no-daemon --stacktrace --continue connectedAndroidTest
      ### Here is the end of conditional steps ###

      # Run tests that does not need AVD
      - name: Run unit tests, lint check and build
        run: ./gradlew --no-daemon --stacktrace --continue test lintDebug assembleDebug

      # Upload results to GitHub Actions
      - name: Upload lint report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html
          if-no-files-found: warn
